### ISSUE TITLE
fix: UncaughtException

### ISSUE THREAD

**Issue by tomassasovsky** [tomassasovsky/radio-horizon.dart#75]
**Description**

Error: autogenerated stack trace for SEVERE Uncaught exception in command: Unknown Message (10008) POST https://discord.com/api/v10/webhooks/977793621896093736/aW50ZXJhY3Rpb246MTA5NjQxMTM1OTQxNzIyNTI0Njp4ZlZvNjNpN05oYUV5dnI0eElob2psM0xHQXE2MGVNRnU0eWlkQkpOMzhHWnRyRW80S1BwOFdZRk8xNVhTSjd2SzFKTllCUlRZTEJ0UFhIdVhUZEFKaEtPejh6b2RIVk10NkJmbjlvVjY5c0hoTFJvS1B3SWRuSlQ3UGhYTlI4QQ
Stack trace:
#0      Logger.log (package:logging/src/logger.dart:200)
#1      Logger.severe (package:logging/src/logger.dart:269)
#2      commandErrorHandler (package:radio_horizon/src/error_handler.dart:81)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#5      _DelayedData.perform (dart:async/stream_impl.dart:515)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

**Comment by tomassasovsky** [comment]
Closing this as it hasn't appeared for a while.
