### ISSUE TITLE
fix: error response throws exception

### ISSUE THREAD

**Issue by tomassasovsky** [tomassasovsky/radio-horizon.dart#76]
**Description**

[2023-04-14 12:28:20.963464] [FINE] [Http] Handling response (404) from request POST https://discord.com/api/v10/webhooks/...
[2023-04-14 12:28:20.963975] [SHOUT] [IgnoreExceptions] Unhandled exception was thrown
Error: Unknown Message (10008) POST https://discord.com/api/v10/webhooks/....
Stack trace:
#0      HttpEndpoints.executeSafe (package:nyxx/src/internal/http_endpoints.dart:428)
<asynchronous suspension>
#1      InteractionsEndpoints.executeSafe (package:nyxx_interactions/src/internal/interaction_endpoints.dart:125)
<asynchronous suspension>
#2      InteractionsEndpoints.sendFollowup (package:nyxx_interactions/src/internal/interaction_endpoints.dart:239)
<asynchronous suspension>
#3      commandErrorHandler (package:radio_horizon/src/error_handler.dart:95)
<asynchronous suspension>

**Comment by tomassasovsky** [comment]
Closing this as it hasn't appeared for a while.
